name: Checkmarx One Scan
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: pzarr/freeSQLi
          cx_tenant: cx_seg
          base_uri: https://eu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --debug --report-format sarif --scs-engines scorecard --scs-repo-url https://github.com/${{ github.repository }} --scs-repo-token ${{ secrets.GH_TOKEN }}
      - name: Upload XML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cx_result.sarif
          path: cx_result.sarif
      - name: Upload Checkmarx SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif
